# Generated by Django 4.1.5 on 2023-01-10 11:40

import coding.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True, validators=[coding.validators.validate_no_special_characters]),
        ),
    ]
